version: '3.8'
services:
  simple-producer:
    build:
      context: ./dockerfile_folder
      dockerfile: Dockerfile.producer 
    container_name: kafka-producer
    volumes:
      - ./kafka_producers/0519_kafka_producer_v2.py/:/app/0519_kafka_producer_v2.py

    networks:
      - my-simple-network

networks:
  my-simple-network:
    external: true

