version: '3.8'
services:
  simple-producer:
    build:
      context: ./dockerfile_folder
      dockerfile: Dockerfile.producer 
    container_name: kafka-producer
    volumes:
      - ./kafka_producers/0524_kafka_producer_latest.py:/app/0524_kafka_producer_latest.py
      - ./kafka_producers/login_events.py:/app/login_events.py
      - ./avro/:/app/avro/
    networks:
      - my-simple-network

networks:
  my-simple-network:
    external: true

