version: '3.8'

services:
  master:
    image: bitnami/spark:3.3.2
    container_name: spark-node
    ports:
      - '8080:8080'
      - '7077:7077'
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark_data:/bitnami/spark/data
      - ./myspark-application/0501_kafka_consumer.py:/0501_kafka_consumer.py
    networks:
      - my-simple-network

networks:
  my-simple-network:
    external: true


