version: '3'
services:
  jupyter:
    build:
      context: ./dockerfile_folder
      dockerfile: Dockerfile.es_client
    container_name: jupyter-notebook
    user: 1001:root
    ports:
      - 8888:8888
    volumes:
      - ./es_client/es_client_for_visualization.ipynb/:/home/jovyan/work/es_client_for_visualization.ipynb
      - ./ca.crt:/home/jovyan/work/ca.crt:ro
    environment:
      - CA_CERT_PATH=./ca.crt
      - ES_PASSWORD=2KeW2V6tKyJaz9gu
    networks:
      - my-simple-network

networks:
  my-simple-network:
    external: true

