version: '3.8'

services:
  master:
    build:
      context: ./dockerfile_folder
      dockerfile: Dockerfile.spark
    container_name: spark-node
    ports:
      - '8080:8080'
      - '7077:7077'
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark_data:/bitnami/spark/data
      - ./spark_consumers/0526_kafka_consumer.py:/0526_kafka_consumer.py
      - ./pyspark_conda_env.tar.gz:/pyspark_conda_env.tar.gz
      - ./ca.crt:/etc/ssl/certs/elasticsearch/ca.crt:ro
      - ./spark_data_checkpoint:/checkpoint 
      - ./avro/:/app/avro/ 
    networks:
      - my-simple-network

networks:
  my-simple-network:
    external: true


