version: '3.8'

services:
  master:
    image: bitnami/spark:3.3.2
    container_name: spark-node
    ports:
      - '8080:8080'
      - '7077:7077'
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark_data:/bitnami/spark/data
      - ./spark_consumers/0519_kafka_consumer.py:/0519_kafka_consumer.py
      - ./ca.crt:/etc/ssl/certs/elasticsearch/ca.crt:ro
      - ./spark_data_checkpoint:/checkpoint  
    networks:
      - my-simple-network

networks:
  my-simple-network:
    external: true


