# Stage 1: Build dependencies
FROM python:3.9-slim AS builder

RUN apt-get update \
    && apt-get install -y build-essential

# Install Python dependencies
RUN pip install confluent-kafka urllib3 requests avro-python3 fastavro

# Stage 2: Final image
FROM python:3.9-slim

WORKDIR /app

# Copy required files from the builder stage
COPY --from=builder /usr/local /usr/local

CMD ["python", "0524_kafka_producer_latest.py"]

